# Generated by Django 5.0.6 on 2024-06-24 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-date_requested"]},
        ),
    ]
