# Generated by Django 5.0.6 on 2024-09-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_request", "0002_alter_request_options"),
        ("records", "0002_alter_records_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="check_up",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="records.records",
            ),
        ),
    ]
