# Generated by Django 5.1.1 on 2024-10-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Illness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("illness_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="records",
            name="illness",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="records.illness",
            ),
        ),
    ]
