# Generated by Django 5.0.6 on 2024-09-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        ("records", "0002_alter_records_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="records",
            name="patient",
        ),
        migrations.AddField(
            model_name="records",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
    ]
