# Generated by Django 5.0.6 on 2024-09-24 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_remove_records_patient_records_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="records",
            name="added_by",
        ),
    ]
