# Generated by Django 5.0.6 on 2024-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0004_remove_records_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
    ]
