# Generated by Django 5.0.6 on 2024-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("DOB", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("contact", models.TextField()),
                ("added", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-added"],
            },
        ),
    ]
