# Generated by Django 5.1.1 on 2024-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="civil_status",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="education",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="employment_status",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="facility_household_no",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="family_member",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="household_no",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_4ps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_nhts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_pcb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_philhealth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="maiden_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="member_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="middle_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mother_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="philhealth_no",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="spouse_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="status_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="suffix",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="contact",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
