# Generated by Django 5.1.1 on 2024-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_blood_type_patient_civil_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="birth_place",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
