# Generated by Django 5.1.1 on 2024-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patient_birth_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="member_category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
