# Generated by Django 5.1.1 on 2024-10-13 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_patient_member_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="member_type",
        ),
    ]
