# Generated by Django 5.1.1 on 2024-10-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_remove_patient_member_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contact",
            field=models.IntegerField(null=True),
        ),
    ]
