# Generated by Django 5.1.1 on 2024-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_patient_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contact",
            field=models.BigIntegerField(null=True),
        ),
    ]
